export const cartActionTypes = {
   TOGGLE_CART: 'TOGGLE_CART',
   ADD_ITEM: 'ADD_ITEM',
   REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
   DECREASE_ITEM: 'DECREASE_ITEM',
   RESET_CART: 'RESET_CART'
};